### ISSUE TITLE
Argument "disable_notification" not working for send_photo method

### ISSUE THREAD

**Issue by un1t** [szastupov/aiotg#49]
Hi!
Thanks for this library, it's cool!

Not sure why, but "disable_notification" not working for send_photo,

    with open('assets/some.jpg', 'rb') as f:
        await chat.send_photo(f, caption='example', disable_notification=True)

Here is trace:

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
        result = coro.throw(exc)
      File "aiobot.py", line 62, in start
        await chat.send_photo(f, caption='example', disable_notification=True)
      File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
        yield self  # This tells Task to wait for completion.
      File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
        future.result()
      File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
        result = coro.send(None)
      File "/var/workspace/mybot/python3/lib/python3.5/site-packages/aiotg/bot.py", line 319, in _api_call
        response = await self.session.post(url, data=params)
      File "/var/workspace/mybot/python3/lib/python3.5/site-packages/aiohttp/helpers.py", line 102, in __await__
        ret = yield from self._coro
      File "/var/workspace/mybot/python3/lib/python3.5/site-packages/aiohttp/client.py", line 226, in _request
        session=self)
      File "/var/workspace/mybot/python3/lib/python3.5/site-packages/aiohttp/client_reqrep.py", line 104, in __init__
        self.update_body_from_data(data)
      File "/var/workspace/mybot/python3/lib/python3.5/site-packages/aiohttp/client_reqrep.py", line 264, in update_body_from_data
        body = FormData(body)()
      File "/var/workspace/mybot/python3/lib/python3.5/site-packages/aiohttp/formdata.py", line 141, in __call__
        return self._gen_form_data()
      File "/var/workspace/mybot/python3/lib/python3.5/site-packages/aiohttp/formdata.py", line 125, in _gen_form_data
        type(value), headers, value)) from exc
    TypeError: Can not serialize value type: <class 'bool'>

Without this argument all works fine!

**Comment by szastupov** [comment]
This is a known issue with form data. Try to pass 'true' as string.

**Comment by un1t** [comment]
Thank for answer. This works.
